source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'bower-rails'

group :development, :test do
    gem 'byebug'
    gem 'web-console', '~> 2.0'
    gem 'spring'
    gem 'rspec'
    gem 'rspec-rails'
    gem 'factory_girl_rails'
    gem 'capybara'
    gem 'database_cleaner'
    gem 'selenium-webdriver'
    gem 'better_errors'
    gem 'pry-rails'
    gem 'annotate', '2.6.5'
end
